[phases.setup]
nixPkgs = ["ffmpeg", "python311", "gcc"]

[phases.install]
cmds = [
  "pip install poetry",
  "poetry config virtualenvs.create false",
  "poetry install --no-interaction --no-ansi"
]

[start]
cmd = "python main.py"
